# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ares_cz"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josef Pospisil"]
  s.date = "2012-10-05"
  s.description = "Simple library for querying Ares system in Czech republic with translation of labels."
  s.email = "pepe@gravastar.cz"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "ares_cz.gemspec",
    "lib/ares_cz.rb",
    "spec/ares_cz_spec.rb"
  ]
  s.homepage = "http://github.com/pepe/ares"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple ruby wrapper for Czech Ares service"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<crack>, [">= 0.1.4"])
    else
      s.add_dependency(%q<crack>, [">= 0.1.4"])
    end
  else
    s.add_dependency(%q<crack>, [">= 0.1.4"])
  end
end

